In [1]:
import numpy as np

In [4]:
def softmax_func(normalized):
    raised = np.exp(normalized)
    output = raised / np.sum(raised, axis=1).reshape(-1,1)
    return output

In [5]:
x = np.random.rand(5, 3)

In [6]:
y = np.zeros_like(x)

In [7]:
inds = (np.arange(0, y.shape[0]), np.random.randint(0, 3, size=y.shape[0]))

In [8]:
y[inds] = 1

In [9]:
x

array([[0.5575675 , 0.06304497, 0.49941283],
       [0.38466069, 0.35641535, 0.94931915],
       [0.91027628, 0.87025495, 0.00973031],
       [0.41708155, 0.91012695, 0.32481429],
       [0.15977601, 0.69847477, 0.65631298]])

In [10]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [11]:
normalized = x - np.max(x, axis=-1).reshape(-1,1)

In [12]:
normalized

array([[ 0.        , -0.49452252, -0.05815467],
       [-0.56465847, -0.5929038 ,  0.        ],
       [ 0.        , -0.04002133, -0.90054597],
       [-0.4930454 ,  0.        , -0.58531266],
       [-0.53869876,  0.        , -0.04216179]])

In [13]:
softmax_func(normalized)

array([[0.39163989, 0.2388463 , 0.36951381],
       [0.26802489, 0.26056035, 0.47141476],
       [0.42245488, 0.40588153, 0.17166359],
       [0.28175711, 0.46131946, 0.25692343],
       [0.22952642, 0.39335672, 0.37711686]])

staged softmax

In [14]:
5/4

1.25

In [15]:
4**-1

0.25

In [16]:
raised = np.exp(x) # step 1

In [17]:
summed = np.sum(raised, axis=-1).reshape(-1,1) # step 2.

In [18]:
pow = summed ** -1
staged_softmax = raised * pow

In [19]:
staged_softmax

array([[0.39163989, 0.2388463 , 0.36951381],
       [0.26802489, 0.26056035, 0.47141476],
       [0.42245488, 0.40588153, 0.17166359],
       [0.28175711, 0.46131946, 0.25692343],
       [0.22952642, 0.39335672, 0.37711686]])

In [20]:
raised

array([[1.74641916, 1.06507474, 1.64775347],
       [1.46911574, 1.42820063, 2.58394979],
       [2.485009  , 2.38751947, 1.00977781],
       [1.51752626, 2.48463794, 1.38377364],
       [1.17324805, 2.01068362, 1.92767186]])

In [22]:
def nll_grad(y, pred):
    return -1 * y / pred

loss_grad = nll_grad(y, staged_softmax)

In [26]:
loss_grad

array([[-2.55336604, -0.        , -0.        ],
       [-3.73099682, -0.        , -0.        ],
       [-0.        , -2.46377311, -0.        ],
       [-0.        , -2.16769524, -0.        ],
       [-0.        , -2.5422217 , -0.        ]])

In [28]:
import sys, os
sys.path.append(os.path.abspath("../nnets"))
from graph import Node, Parameter, display_chain

ModuleNotFoundError: No module named 'graph'

In [33]:
class Exp(Node):
    def forward(self, x):
        return np.exp(x)

    def backward(self, grad):
        x = self.cache[0]
        return np.exp(x) * grad

class Sum(Node):
    def forward(self, x):
        return np.sum(x, axis=-1).reshape(-1,1)

    def backward(self, grad):
        x = self.cache

class Pow(Node):
    def forward(self, x, exponent):
        return x ** exponent

    def backward(self, grad):
        x, exponent = self.cache
        return grad * exponent * x  ** (exponent - 1), 1

class Multiply(Node):
    def forward(self, x, y):
        return x * y
    def backward(self, grad):
        x, y = self.cache
        return grad * y, grad * x

NameError: name 'Node' is not defined